<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Zipcode;

class ZipcodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->zipcodes as $zipcode) {
            Zipcode::create($zipcode);
        }
    }

    private $zipcodes = [
        ['zipcode' => 2000, 'city' => 'Frederiksberg', 'country_id' => 1],
        ['zipcode' => 2100, 'city' => 'København Ø', 'country_id' => 1],
        ['zipcode' => 2150, 'city' => 'Nordhavn', 'country_id' => 1],
        ['zipcode' => 2200, 'city' => 'København N', 'country_id' => 1],
        ['zipcode' => 2300, 'city' => 'København S', 'country_id' => 1],
        ['zipcode' => 2400, 'city' => 'København NV', 'country_id' => 1],
        ['zipcode' => 2450, 'city' => 'København SV', 'country_id' => 1],
        ['zipcode' => 2500, 'city' => 'Valby', 'country_id' => 1],
        ['zipcode' => 2600, 'city' => 'Glostrup', 'country_id' => 1],
        ['zipcode' => 2605, 'city' => 'Brøndby', 'country_id' => 1],
        ['zipcode' => 2610, 'city' => 'Rødovre', 'country_id' => 1],
        ['zipcode' => 2620, 'city' => 'Albertslund', 'country_id' => 1],
        ['zipcode' => 2625, 'city' => 'Vallensbæk', 'country_id' => 1],
        ['zipcode' => 2630, 'city' => 'Taastrup', 'country_id' => 1],
        ['zipcode' => 2635, 'city' => 'Ishøj', 'country_id' => 1],
        ['zipcode' => 2640, 'city' => 'Hedehusene', 'country_id' => 1],
        ['zipcode' => 2650, 'city' => 'Hvidovre', 'country_id' => 1],
        ['zipcode' => 2660, 'city' => 'Brøndby Strand', 'country_id' => 1],
        ['zipcode' => 2665, 'city' => 'Vallensbæk Strand', 'country_id' => 1],
        ['zipcode' => 2670, 'city' => 'Greve', 'country_id' => 1],
        ['zipcode' => 2680, 'city' => 'Solrød Strand', 'country_id' => 1],
        ['zipcode' => 2690, 'city' => 'Karlslunde', 'country_id' => 1],
        ['zipcode' => 2700, 'city' => 'Brønshøj', 'country_id' => 1],
        ['zipcode' => 2720, 'city' => 'Vanløse', 'country_id' => 1],
        ['zipcode' => 2730, 'city' => 'Herlev', 'country_id' => 1],
        ['zipcode' => 2740, 'city' => 'Skovlunde', 'country_id' => 1],
        ['zipcode' => 2750, 'city' => 'Ballerup', 'country_id' => 1],
        ['zipcode' => 2760, 'city' => 'Måløv', 'country_id' => 1],
        ['zipcode' => 2765, 'city' => 'Smørum', 'country_id' => 1],
        ['zipcode' => 2770, 'city' => 'Kastrup', 'country_id' => 1],
        ['zipcode' => 2791, 'city' => 'Dragør', 'country_id' => 1],
        ['zipcode' => 2800, 'city' => 'Kongens Lyngby', 'country_id' => 1],
        ['zipcode' => 2820, 'city' => 'Gentofte', 'country_id' => 1],
        ['zipcode' => 2830, 'city' => 'Virum', 'country_id' => 1],
        ['zipcode' => 2840, 'city' => 'Holte', 'country_id' => 1],
        ['zipcode' => 2850, 'city' => 'Nærum', 'country_id' => 1],
        ['zipcode' => 2860, 'city' => 'Søborg', 'country_id' => 1],
        ['zipcode' => 2870, 'city' => 'Dyssegård', 'country_id' => 1],
        ['zipcode' => 2880, 'city' => 'Bagsværd', 'country_id' => 1],
        ['zipcode' => 2900, 'city' => 'Hellerup', 'country_id' => 1],
        ['zipcode' => 2920, 'city' => 'Charlottenlund', 'country_id' => 1],
        ['zipcode' => 2930, 'city' => 'Klampenborg', 'country_id' => 1],
        ['zipcode' => 2942, 'city' => 'Skodsborg', 'country_id' => 1],
        ['zipcode' => 2950, 'city' => 'Vedbæk', 'country_id' => 1],
        ['zipcode' => 2960, 'city' => 'Rungsted Kyst', 'country_id' => 1],
        ['zipcode' => 2970, 'city' => 'Hørsholm', 'country_id' => 1],
        ['zipcode' => 2980, 'city' => 'Kokkedal', 'country_id' => 1],
        ['zipcode' => 2990, 'city' => 'Nivå', 'country_id' => 1],
        ['zipcode' => 3000, 'city' => 'Helsingør', 'country_id' => 1],
        ['zipcode' => 3050, 'city' => 'Humlebæk', 'country_id' => 1],
        ['zipcode' => 3060, 'city' => 'Espergærde', 'country_id' => 1],
        ['zipcode' => 3070, 'city' => 'Snekkersten', 'country_id' => 1],
        ['zipcode' => 3080, 'city' => 'Tikøb', 'country_id' => 1],
        ['zipcode' => 3100, 'city' => 'Hornbæk', 'country_id' => 1],
        ['zipcode' => 3120, 'city' => 'Dronningmølle', 'country_id' => 1],
        ['zipcode' => 3140, 'city' => 'Ålsgårde', 'country_id' => 1],
        ['zipcode' => 3150, 'city' => 'Hellebæk', 'country_id' => 1],
        ['zipcode' => 3200, 'city' => 'Helsinge', 'country_id' => 1],
        ['zipcode' => 3210, 'city' => 'Vejby', 'country_id' => 1],
        ['zipcode' => 3220, 'city' => 'Tisvildeleje', 'country_id' => 1],
        ['zipcode' => 3230, 'city' => 'Græsted', 'country_id' => 1],
        ['zipcode' => 3250, 'city' => 'Gilleleje', 'country_id' => 1],
        ['zipcode' => 3300, 'city' => 'Frederiksværk', 'country_id' => 1],
        ['zipcode' => 3310, 'city' => 'Ølsted', 'country_id' => 1],
        ['zipcode' => 3320, 'city' => 'Skævinge', 'country_id' => 1],
        ['zipcode' => 3330, 'city' => 'Gørløse', 'country_id' => 1],
        ['zipcode' => 3360, 'city' => 'Liseleje', 'country_id' => 1],
        ['zipcode' => 3370, 'city' => 'Melby', 'country_id' => 1],
        ['zipcode' => 3390, 'city' => 'Hundested', 'country_id' => 1],
        ['zipcode' => 3400, 'city' => 'Hillerød', 'country_id' => 1],
        ['zipcode' => 3450, 'city' => 'Allerød', 'country_id' => 1],
        ['zipcode' => 3460, 'city' => 'Birkerød', 'country_id' => 1],
        ['zipcode' => 3480, 'city' => 'Fredensborg', 'country_id' => 1],
        ['zipcode' => 3490, 'city' => 'Kvistgård', 'country_id' => 1],
        ['zipcode' => 3500, 'city' => 'Værløse', 'country_id' => 1],
        ['zipcode' => 3520, 'city' => 'Farum', 'country_id' => 1],
        ['zipcode' => 3540, 'city' => 'Lynge', 'country_id' => 1],
        ['zipcode' => 3550, 'city' => 'Slangerup', 'country_id' => 1],
        ['zipcode' => 3600, 'city' => 'Frederikssund', 'country_id' => 1],
        ['zipcode' => 3630, 'city' => 'Jægerspris', 'country_id' => 1],
        ['zipcode' => 3650, 'city' => 'Ølstykke', 'country_id' => 1],
        ['zipcode' => 3660, 'city' => 'Stenløse', 'country_id' => 1],
        ['zipcode' => 3670, 'city' => 'Veksø Sjælland', 'country_id' => 1],
        ['zipcode' => 3700, 'city' => 'Rønne', 'country_id' => 1],
        ['zipcode' => 3720, 'city' => 'Aakirkeby', 'country_id' => 1],
        ['zipcode' => 3730, 'city' => 'Nexø', 'country_id' => 1],
        ['zipcode' => 3740, 'city' => 'Svaneke', 'country_id' => 1],
        ['zipcode' => 3751, 'city' => 'Østermarie', 'country_id' => 1],
        ['zipcode' => 3760, 'city' => 'Gudhjem', 'country_id' => 1],
        ['zipcode' => 3770, 'city' => 'Allinge', 'country_id' => 1],
        ['zipcode' => 3782, 'city' => 'Klemensker', 'country_id' => 1],
        ['zipcode' => 3790, 'city' => 'Hasle', 'country_id' => 1],
        ['zipcode' => 4000, 'city' => 'Roskilde', 'country_id' => 1],
        ['zipcode' => 4030, 'city' => 'Tune', 'country_id' => 1],
        ['zipcode' => 4040, 'city' => 'Jyllinge', 'country_id' => 1],
        ['zipcode' => 4050, 'city' => 'Skibby', 'country_id' => 1],
        ['zipcode' => 4060, 'city' => 'Kirke Såby', 'country_id' => 1],
        ['zipcode' => 4070, 'city' => 'Kirke Hyllinge', 'country_id' => 1],
        ['zipcode' => 4100, 'city' => 'Ringsted', 'country_id' => 1],
        ['zipcode' => 4130, 'city' => 'Viby Sjælland', 'country_id' => 1],
        ['zipcode' => 4140, 'city' => 'Borup', 'country_id' => 1],
        ['zipcode' => 4160, 'city' => 'Herlufmagle', 'country_id' => 1],
        ['zipcode' => 4171, 'city' => 'Glumsø', 'country_id' => 1],
        ['zipcode' => 4173, 'city' => 'Fjenneslev', 'country_id' => 1],
        ['zipcode' => 4174, 'city' => 'Jystrup Midtsj', 'country_id' => 1],
        ['zipcode' => 4180, 'city' => 'Sorø', 'country_id' => 1],
        ['zipcode' => 4190, 'city' => 'Munke Bjergby', 'country_id' => 1],
        ['zipcode' => 4200, 'city' => 'Slagelse', 'country_id' => 1],
        ['zipcode' => 4220, 'city' => 'Korsør', 'country_id' => 1],
        ['zipcode' => 4230, 'city' => 'Skælskør', 'country_id' => 1],
        ['zipcode' => 4241, 'city' => 'Vemmelev', 'country_id' => 1],
        ['zipcode' => 4242, 'city' => 'Boeslunde', 'country_id' => 1],
        ['zipcode' => 4243, 'city' => 'Rude', 'country_id' => 1],
        ['zipcode' => 4244, 'city' => 'Agersø', 'country_id' => 1],
        ['zipcode' => 4245, 'city' => 'Omø', 'country_id' => 1],
        ['zipcode' => 4250, 'city' => 'Fuglebjerg', 'country_id' => 1],
        ['zipcode' => 4261, 'city' => 'Dalmose', 'country_id' => 1],
        ['zipcode' => 4262, 'city' => 'Sandved', 'country_id' => 1],
        ['zipcode' => 4270, 'city' => 'Høng', 'country_id' => 1],
        ['zipcode' => 4281, 'city' => 'Gørlev', 'country_id' => 1],
        ['zipcode' => 4291, 'city' => 'Ruds Vedby', 'country_id' => 1],
        ['zipcode' => 4293, 'city' => 'Dianalund', 'country_id' => 1],
        ['zipcode' => 4295, 'city' => 'Stenlille', 'country_id' => 1],
        ['zipcode' => 4296, 'city' => 'Nyrup', 'country_id' => 1],
        ['zipcode' => 4300, 'city' => 'Holbæk', 'country_id' => 1],
        ['zipcode' => 4305, 'city' => 'Orø', 'country_id' => 1],
        ['zipcode' => 4320, 'city' => 'Lejre', 'country_id' => 1],
        ['zipcode' => 4330, 'city' => 'Hvalsø', 'country_id' => 1],
        ['zipcode' => 4340, 'city' => 'Tølløse', 'country_id' => 1],
        ['zipcode' => 4350, 'city' => 'Ugerløse', 'country_id' => 1],
        ['zipcode' => 4360, 'city' => 'Kirke Eskilstrup', 'country_id' => 1],
        ['zipcode' => 4370, 'city' => 'Store Merløse', 'country_id' => 1],
        ['zipcode' => 4390, 'city' => 'Vipperød', 'country_id' => 1],
        ['zipcode' => 4400, 'city' => 'Kalundborg', 'country_id' => 1],
        ['zipcode' => 4420, 'city' => 'Regstrup', 'country_id' => 1],
        ['zipcode' => 4440, 'city' => 'Mørkøv', 'country_id' => 1],
        ['zipcode' => 4450, 'city' => 'Jyderup', 'country_id' => 1],
        ['zipcode' => 4460, 'city' => 'Snertinge', 'country_id' => 1],
        ['zipcode' => 4470, 'city' => 'Svebølle', 'country_id' => 1],
        ['zipcode' => 4480, 'city' => 'Store Fuglede', 'country_id' => 1],
        ['zipcode' => 4490, 'city' => 'Jerslev Sjælland', 'country_id' => 1],
        ['zipcode' => 4500, 'city' => 'Nykøbing Sj', 'country_id' => 1],
        ['zipcode' => 4520, 'city' => 'Svinninge', 'country_id' => 1],
        ['zipcode' => 4532, 'city' => 'Gislinge', 'country_id' => 1],
        ['zipcode' => 4534, 'city' => 'Hørve', 'country_id' => 1],
        ['zipcode' => 4540, 'city' => 'Fårevejle', 'country_id' => 1],
        ['zipcode' => 4550, 'city' => 'Asnæs', 'country_id' => 1],
        ['zipcode' => 4560, 'city' => 'Vig', 'country_id' => 1],
        ['zipcode' => 4571, 'city' => 'Grevinge', 'country_id' => 1],
        ['zipcode' => 4572, 'city' => 'Nørre Asmindrup', 'country_id' => 1],
        ['zipcode' => 4573, 'city' => 'Højby', 'country_id' => 1],
        ['zipcode' => 4581, 'city' => 'Rørvig', 'country_id' => 1],
        ['zipcode' => 4583, 'city' => 'Sjællands Odde', 'country_id' => 1],
        ['zipcode' => 4591, 'city' => 'Føllenslev', 'country_id' => 1],
        ['zipcode' => 4592, 'city' => 'Sejerø', 'country_id' => 1],
        ['zipcode' => 4593, 'city' => 'Eskebjerg', 'country_id' => 1],
        ['zipcode' => 4600, 'city' => 'Køge', 'country_id' => 1],
        ['zipcode' => 4621, 'city' => 'Gadstrup', 'country_id' => 1],
        ['zipcode' => 4622, 'city' => 'Havdrup', 'country_id' => 1],
        ['zipcode' => 4623, 'city' => 'Lille Skensved', 'country_id' => 1],
        ['zipcode' => 4632, 'city' => 'Bjæverskov', 'country_id' => 1],
        ['zipcode' => 4640, 'city' => 'Faxe', 'country_id' => 1],
        ['zipcode' => 4652, 'city' => 'Hårlev', 'country_id' => 1],
        ['zipcode' => 4653, 'city' => 'Karise', 'country_id' => 1],
        ['zipcode' => 4654, 'city' => 'Faxe Ladeplads', 'country_id' => 1],
        ['zipcode' => 4660, 'city' => 'Store Heddinge', 'country_id' => 1],
        ['zipcode' => 4671, 'city' => 'Strøby', 'country_id' => 1],
        ['zipcode' => 4672, 'city' => 'Klippinge', 'country_id' => 1],
        ['zipcode' => 4673, 'city' => 'Rødvig Stevns', 'country_id' => 1],
        ['zipcode' => 4681, 'city' => 'Herfølge', 'country_id' => 1],
        ['zipcode' => 4682, 'city' => 'Tureby', 'country_id' => 1],
        ['zipcode' => 4683, 'city' => 'Rønnede', 'country_id' => 1],
        ['zipcode' => 4684, 'city' => 'Holmegaard', 'country_id' => 1],
        ['zipcode' => 4690, 'city' => 'Haslev', 'country_id' => 1],
        ['zipcode' => 4700, 'city' => 'Næstved', 'country_id' => 1],
        ['zipcode' => 4720, 'city' => 'Præstø', 'country_id' => 1],
        ['zipcode' => 4733, 'city' => 'Tappernøje', 'country_id' => 1],
        ['zipcode' => 4735, 'city' => 'Mern', 'country_id' => 1],
        ['zipcode' => 4736, 'city' => 'Karrebæksminde', 'country_id' => 1],
        ['zipcode' => 4750, 'city' => 'Lundby', 'country_id' => 1],
        ['zipcode' => 4760, 'city' => 'Vordingborg', 'country_id' => 1],
        ['zipcode' => 4771, 'city' => 'Kalvehave', 'country_id' => 1],
        ['zipcode' => 4772, 'city' => 'Langebæk', 'country_id' => 1],
        ['zipcode' => 4773, 'city' => 'Stensved', 'country_id' => 1],
        ['zipcode' => 4780, 'city' => 'Stege', 'country_id' => 1],
        ['zipcode' => 4791, 'city' => 'Borre', 'country_id' => 1],
        ['zipcode' => 4792, 'city' => 'Askeby', 'country_id' => 1],
        ['zipcode' => 4793, 'city' => 'Bogø By', 'country_id' => 1],
        ['zipcode' => 4800, 'city' => 'Nykøbing F', 'country_id' => 1],
        ['zipcode' => 4840, 'city' => 'Nørre Alslev', 'country_id' => 1],
        ['zipcode' => 4850, 'city' => 'Stubbekøbing', 'country_id' => 1],
        ['zipcode' => 4862, 'city' => 'Guldborg', 'country_id' => 1],
        ['zipcode' => 4863, 'city' => 'Eskilstrup', 'country_id' => 1],
        ['zipcode' => 4871, 'city' => 'Horbelev', 'country_id' => 1],
        ['zipcode' => 4872, 'city' => 'Idestrup', 'country_id' => 1],
        ['zipcode' => 4873, 'city' => 'Væggerløse', 'country_id' => 1],
        ['zipcode' => 4874, 'city' => 'Gedser', 'country_id' => 1],
        ['zipcode' => 4880, 'city' => 'Nysted', 'country_id' => 1],
        ['zipcode' => 4891, 'city' => 'Toreby L', 'country_id' => 1],
        ['zipcode' => 4892, 'city' => 'Kettinge', 'country_id' => 1],
        ['zipcode' => 4894, 'city' => 'Øster Ulslev', 'country_id' => 1],
        ['zipcode' => 4895, 'city' => 'Errindlev', 'country_id' => 1],
        ['zipcode' => 4900, 'city' => 'Nakskov', 'country_id' => 1],
        ['zipcode' => 4912, 'city' => 'Harpelunde', 'country_id' => 1],
        ['zipcode' => 4913, 'city' => 'Horslunde', 'country_id' => 1],
        ['zipcode' => 4920, 'city' => 'Søllested', 'country_id' => 1],
        ['zipcode' => 4930, 'city' => 'Maribo', 'country_id' => 1],
        ['zipcode' => 4941, 'city' => 'Bandholm', 'country_id' => 1],
        ['zipcode' => 4942, 'city' => 'Askø og Lilleø', 'country_id' => 1],
        ['zipcode' => 4943, 'city' => 'Torrig L', 'country_id' => 1],
        ['zipcode' => 4944, 'city' => 'Fejø', 'country_id' => 1],
        ['zipcode' => 4945, 'city' => 'Femø', 'country_id' => 1],
        ['zipcode' => 4951, 'city' => 'Nørreballe', 'country_id' => 1],
        ['zipcode' => 4952, 'city' => 'Stokkemarke', 'country_id' => 1],
        ['zipcode' => 4953, 'city' => 'Vesterborg', 'country_id' => 1],
        ['zipcode' => 4960, 'city' => 'Holeby', 'country_id' => 1],
        ['zipcode' => 4970, 'city' => 'Rødby', 'country_id' => 1],
        ['zipcode' => 4983, 'city' => 'Dannemare', 'country_id' => 1],
        ['zipcode' => 4990, 'city' => 'Sakskøbing', 'country_id' => 1],
        ['zipcode' => 5000, 'city' => 'Odense C', 'country_id' => 1],
        ['zipcode' => 5200, 'city' => 'Odense V', 'country_id' => 1],
        ['zipcode' => 5210, 'city' => 'Odense NV', 'country_id' => 1],
        ['zipcode' => 5220, 'city' => 'Odense SØ', 'country_id' => 1],
        ['zipcode' => 5230, 'city' => 'Odense M', 'country_id' => 1],
        ['zipcode' => 5240, 'city' => 'Odense NØ', 'country_id' => 1],
        ['zipcode' => 5250, 'city' => 'Odense SV', 'country_id' => 1],
        ['zipcode' => 5260, 'city' => 'Odense S', 'country_id' => 1],
        ['zipcode' => 5270, 'city' => 'Odense N', 'country_id' => 1],
        ['zipcode' => 5290, 'city' => 'Marslev', 'country_id' => 1],
        ['zipcode' => 5300, 'city' => 'Kerteminde', 'country_id' => 1],
        ['zipcode' => 5320, 'city' => 'Agedrup', 'country_id' => 1],
        ['zipcode' => 5330, 'city' => 'Munkebo', 'country_id' => 1],
        ['zipcode' => 5350, 'city' => 'Rynkeby', 'country_id' => 1],
        ['zipcode' => 5370, 'city' => 'Mesinge', 'country_id' => 1],
        ['zipcode' => 5380, 'city' => 'Dalby', 'country_id' => 1],
        ['zipcode' => 5390, 'city' => 'Martofte', 'country_id' => 1],
        ['zipcode' => 5400, 'city' => 'Bogense', 'country_id' => 1],
        ['zipcode' => 5450, 'city' => 'Otterup', 'country_id' => 1],
        ['zipcode' => 5462, 'city' => 'Morud', 'country_id' => 1],
        ['zipcode' => 5463, 'city' => 'Harndrup', 'country_id' => 1],
        ['zipcode' => 5464, 'city' => 'Brenderup Fyn', 'country_id' => 1],
        ['zipcode' => 5466, 'city' => 'Asperup', 'country_id' => 1],
        ['zipcode' => 5471, 'city' => 'Søndersø', 'country_id' => 1],
        ['zipcode' => 5474, 'city' => 'Veflinge', 'country_id' => 1],
        ['zipcode' => 5485, 'city' => 'Skamby', 'country_id' => 1],
        ['zipcode' => 5491, 'city' => 'Blommenslyst', 'country_id' => 1],
        ['zipcode' => 5492, 'city' => 'Vissenbjerg', 'country_id' => 1],
        ['zipcode' => 5500, 'city' => 'Middelfart', 'country_id' => 1],
        ['zipcode' => 5540, 'city' => 'Ullerslev', 'country_id' => 1],
        ['zipcode' => 5550, 'city' => 'Langeskov', 'country_id' => 1],
        ['zipcode' => 5560, 'city' => 'Aarup', 'country_id' => 1],
        ['zipcode' => 5580, 'city' => 'Nørre Aaby', 'country_id' => 1],
        ['zipcode' => 5591, 'city' => 'Gelsted', 'country_id' => 1],
        ['zipcode' => 5592, 'city' => 'Ejby', 'country_id' => 1],
        ['zipcode' => 5600, 'city' => 'Faaborg', 'country_id' => 1],
        ['zipcode' => 5601, 'city' => 'Lyø', 'country_id' => 1],
        ['zipcode' => 5602, 'city' => 'Avernakø', 'country_id' => 1],
        ['zipcode' => 5603, 'city' => 'Bjørnø', 'country_id' => 1],
        ['zipcode' => 5610, 'city' => 'Assens', 'country_id' => 1],
        ['zipcode' => 5620, 'city' => 'Glamsbjerg', 'country_id' => 1],
        ['zipcode' => 5631, 'city' => 'Ebberup', 'country_id' => 1],
        ['zipcode' => 5642, 'city' => 'Millinge', 'country_id' => 1],
        ['zipcode' => 5672, 'city' => 'Broby', 'country_id' => 1],
        ['zipcode' => 5683, 'city' => 'Haarby', 'country_id' => 1],
        ['zipcode' => 5690, 'city' => 'Tommerup', 'country_id' => 1],
        ['zipcode' => 5700, 'city' => 'Svendborg', 'country_id' => 1],
        ['zipcode' => 5750, 'city' => 'Ringe', 'country_id' => 1],
        ['zipcode' => 5762, 'city' => 'Vester Skerninge', 'country_id' => 1],
        ['zipcode' => 5771, 'city' => 'Stenstrup', 'country_id' => 1],
        ['zipcode' => 5772, 'city' => 'Kværndrup', 'country_id' => 1],
        ['zipcode' => 5792, 'city' => 'Årslev', 'country_id' => 1],
        ['zipcode' => 5800, 'city' => 'Nyborg', 'country_id' => 1],
        ['zipcode' => 5853, 'city' => 'Ørbæk', 'country_id' => 1],
        ['zipcode' => 5854, 'city' => 'Gislev', 'country_id' => 1],
        ['zipcode' => 5856, 'city' => 'Ryslinge', 'country_id' => 1],
        ['zipcode' => 5863, 'city' => 'Ferritslev Fyn', 'country_id' => 1],
        ['zipcode' => 5871, 'city' => 'Frørup', 'country_id' => 1],
        ['zipcode' => 5874, 'city' => 'Hesselager', 'country_id' => 1],
        ['zipcode' => 5881, 'city' => 'Skårup Fyn', 'country_id' => 1],
        ['zipcode' => 5882, 'city' => 'Vejstrup', 'country_id' => 1],
        ['zipcode' => 5883, 'city' => 'Oure', 'country_id' => 1],
        ['zipcode' => 5884, 'city' => 'Gudme', 'country_id' => 1],
        ['zipcode' => 5892, 'city' => 'Gudbjerg Sydfyn', 'country_id' => 1],
        ['zipcode' => 5900, 'city' => 'Rudkøbing', 'country_id' => 1],
        ['zipcode' => 5932, 'city' => 'Humble', 'country_id' => 1],
        ['zipcode' => 5935, 'city' => 'Bagenkop', 'country_id' => 1],
        ['zipcode' => 5943, 'city' => 'Strynø', 'country_id' => 1],
        ['zipcode' => 5953, 'city' => 'Tranekær', 'country_id' => 1],
        ['zipcode' => 5960, 'city' => 'Marstal', 'country_id' => 1],
        ['zipcode' => 5965, 'city' => 'Birkholm', 'country_id' => 1],
        ['zipcode' => 5970, 'city' => 'Ærøskøbing', 'country_id' => 1],
        ['zipcode' => 5985, 'city' => 'Søby Ærø', 'country_id' => 1],
        ['zipcode' => 6000, 'city' => 'Kolding', 'country_id' => 1],
        ['zipcode' => 6040, 'city' => 'Egtved', 'country_id' => 1],
        ['zipcode' => 6051, 'city' => 'Almind', 'country_id' => 1],
        ['zipcode' => 6052, 'city' => 'Viuf', 'country_id' => 1],
        ['zipcode' => 6064, 'city' => 'Jordrup', 'country_id' => 1],
        ['zipcode' => 6070, 'city' => 'Christiansfeld', 'country_id' => 1],
        ['zipcode' => 6091, 'city' => 'Bjert', 'country_id' => 1],
        ['zipcode' => 6092, 'city' => 'Sønder Stenderup', 'country_id' => 1],
        ['zipcode' => 6093, 'city' => 'Sjølund', 'country_id' => 1],
        ['zipcode' => 6094, 'city' => 'Hejls', 'country_id' => 1],
        ['zipcode' => 6100, 'city' => 'Haderslev', 'country_id' => 1],
        ['zipcode' => 6200, 'city' => 'Aabenraa', 'country_id' => 1],
        ['zipcode' => 6210, 'city' => 'Barsø', 'country_id' => 1],
        ['zipcode' => 6230, 'city' => 'Rødekro', 'country_id' => 1],
        ['zipcode' => 6240, 'city' => 'Løgumkloster', 'country_id' => 1],
        ['zipcode' => 6261, 'city' => 'Bredebro', 'country_id' => 1],
        ['zipcode' => 6270, 'city' => 'Tønder', 'country_id' => 1],
        ['zipcode' => 6280, 'city' => 'Højer', 'country_id' => 1],
        ['zipcode' => 6300, 'city' => 'Gråsten', 'country_id' => 1],
        ['zipcode' => 6310, 'city' => 'Broager', 'country_id' => 1],
        ['zipcode' => 6320, 'city' => 'Egernsund', 'country_id' => 1],
        ['zipcode' => 6330, 'city' => 'Padborg', 'country_id' => 1],
        ['zipcode' => 6340, 'city' => 'Kruså', 'country_id' => 1],
        ['zipcode' => 6360, 'city' => 'Tinglev', 'country_id' => 1],
        ['zipcode' => 6372, 'city' => 'Bylderup-Bov', 'country_id' => 1],
        ['zipcode' => 6392, 'city' => 'Bolderslev', 'country_id' => 1],
        ['zipcode' => 6400, 'city' => 'Sønderborg', 'country_id' => 1],
        ['zipcode' => 6430, 'city' => 'Nordborg', 'country_id' => 1],
        ['zipcode' => 6440, 'city' => 'Augustenborg', 'country_id' => 1],
        ['zipcode' => 6470, 'city' => 'Sydals', 'country_id' => 1],
        ['zipcode' => 6500, 'city' => 'Vojens', 'country_id' => 1],
        ['zipcode' => 6510, 'city' => 'Gram', 'country_id' => 1],
        ['zipcode' => 6520, 'city' => 'Toftlund', 'country_id' => 1],
        ['zipcode' => 6534, 'city' => 'Agerskov', 'country_id' => 1],
        ['zipcode' => 6535, 'city' => 'Branderup J', 'country_id' => 1],
        ['zipcode' => 6541, 'city' => 'Bevtoft', 'country_id' => 1],
        ['zipcode' => 6560, 'city' => 'Sommersted', 'country_id' => 1],
        ['zipcode' => 6580, 'city' => 'Vamdrup', 'country_id' => 1],
        ['zipcode' => 6600, 'city' => 'Vejen', 'country_id' => 1],
        ['zipcode' => 6621, 'city' => 'Gesten', 'country_id' => 1],
        ['zipcode' => 6622, 'city' => 'Bække', 'country_id' => 1],
        ['zipcode' => 6623, 'city' => 'Vorbasse', 'country_id' => 1],
        ['zipcode' => 6630, 'city' => 'Rødding', 'country_id' => 1],
        ['zipcode' => 6640, 'city' => 'Lunderskov', 'country_id' => 1],
        ['zipcode' => 6650, 'city' => 'Brørup', 'country_id' => 1],
        ['zipcode' => 6660, 'city' => 'Lintrup', 'country_id' => 1],
        ['zipcode' => 6670, 'city' => 'Holsted', 'country_id' => 1],
        ['zipcode' => 6682, 'city' => 'Hovborg', 'country_id' => 1],
        ['zipcode' => 6683, 'city' => 'Føvling', 'country_id' => 1],
        ['zipcode' => 6690, 'city' => 'Gørding', 'country_id' => 1],
        ['zipcode' => 6700, 'city' => 'Esbjerg', 'country_id' => 1],
        ['zipcode' => 6705, 'city' => 'Esbjerg Ø', 'country_id' => 1],
        ['zipcode' => 6710, 'city' => 'Esbjerg V', 'country_id' => 1],
        ['zipcode' => 6715, 'city' => 'Esbjerg N', 'country_id' => 1],
        ['zipcode' => 6720, 'city' => 'Fanø', 'country_id' => 1],
        ['zipcode' => 6731, 'city' => 'Tjæreborg', 'country_id' => 1],
        ['zipcode' => 6740, 'city' => 'Bramming', 'country_id' => 1],
        ['zipcode' => 6752, 'city' => 'Glejbjerg', 'country_id' => 1],
        ['zipcode' => 6753, 'city' => 'Agerbæk', 'country_id' => 1],
        ['zipcode' => 6760, 'city' => 'Ribe', 'country_id' => 1],
        ['zipcode' => 6771, 'city' => 'Gredstedbro', 'country_id' => 1],
        ['zipcode' => 6780, 'city' => 'Skærbæk', 'country_id' => 1],
        ['zipcode' => 6792, 'city' => 'Rømø', 'country_id' => 1],
        ['zipcode' => 6800, 'city' => 'Varde', 'country_id' => 1],
        ['zipcode' => 6818, 'city' => 'Årre', 'country_id' => 1],
        ['zipcode' => 6823, 'city' => 'Ansager', 'country_id' => 1],
        ['zipcode' => 6830, 'city' => 'Nørre Nebel', 'country_id' => 1],
        ['zipcode' => 6840, 'city' => 'Oksbøl', 'country_id' => 1],
        ['zipcode' => 6851, 'city' => 'Janderup Vestj', 'country_id' => 1],
        ['zipcode' => 6852, 'city' => 'Billum', 'country_id' => 1],
        ['zipcode' => 6853, 'city' => 'Vejers Strand', 'country_id' => 1],
        ['zipcode' => 6854, 'city' => 'Henne', 'country_id' => 1],
        ['zipcode' => 6855, 'city' => 'Outrup', 'country_id' => 1],
        ['zipcode' => 6857, 'city' => 'Blåvand', 'country_id' => 1],
        ['zipcode' => 6862, 'city' => 'Tistrup', 'country_id' => 1],
        ['zipcode' => 6870, 'city' => 'Ølgod', 'country_id' => 1],
        ['zipcode' => 6880, 'city' => 'Tarm', 'country_id' => 1],
        ['zipcode' => 6893, 'city' => 'Hemmet', 'country_id' => 1],
        ['zipcode' => 6900, 'city' => 'Skjern', 'country_id' => 1],
        ['zipcode' => 6920, 'city' => 'Videbæk', 'country_id' => 1],
        ['zipcode' => 6933, 'city' => 'Kibæk', 'country_id' => 1],
        ['zipcode' => 6940, 'city' => 'Lem St', 'country_id' => 1],
        ['zipcode' => 6950, 'city' => 'Ringkøbing', 'country_id' => 1],
        ['zipcode' => 6960, 'city' => 'Hvide Sande', 'country_id' => 1],
        ['zipcode' => 6971, 'city' => 'Spjald', 'country_id' => 1],
        ['zipcode' => 6973, 'city' => 'Ørnhøj', 'country_id' => 1],
        ['zipcode' => 6980, 'city' => 'Tim', 'country_id' => 1],
        ['zipcode' => 6990, 'city' => 'Ulfborg', 'country_id' => 1],
        ['zipcode' => 7000, 'city' => 'Fredericia', 'country_id' => 1],
        ['zipcode' => 7080, 'city' => 'Børkop', 'country_id' => 1],
        ['zipcode' => 7100, 'city' => 'Vejle', 'country_id' => 1],
        ['zipcode' => 7120, 'city' => 'Vejle Øst', 'country_id' => 1],
        ['zipcode' => 7130, 'city' => 'Juelsminde', 'country_id' => 1],
        ['zipcode' => 7140, 'city' => 'Stouby', 'country_id' => 1],
        ['zipcode' => 7150, 'city' => 'Barrit', 'country_id' => 1],
        ['zipcode' => 7160, 'city' => 'Tørring', 'country_id' => 1],
        ['zipcode' => 7171, 'city' => 'Uldum', 'country_id' => 1],
        ['zipcode' => 7173, 'city' => 'Vonge', 'country_id' => 1],
        ['zipcode' => 7182, 'city' => 'Bredsten', 'country_id' => 1],
        ['zipcode' => 7183, 'city' => 'Randbøl', 'country_id' => 1],
        ['zipcode' => 7184, 'city' => 'Vandel', 'country_id' => 1],
        ['zipcode' => 7190, 'city' => 'Billund', 'country_id' => 1],
        ['zipcode' => 7200, 'city' => 'Grindsted', 'country_id' => 1],
        ['zipcode' => 7250, 'city' => 'Hejnsvig', 'country_id' => 1],
        ['zipcode' => 7260, 'city' => 'Sønder Omme', 'country_id' => 1],
        ['zipcode' => 7270, 'city' => 'Stakroge', 'country_id' => 1],
        ['zipcode' => 7280, 'city' => 'Sønder Felding', 'country_id' => 1],
        ['zipcode' => 7300, 'city' => 'Jelling', 'country_id' => 1],
        ['zipcode' => 7321, 'city' => 'Gadbjerg', 'country_id' => 1],
        ['zipcode' => 7323, 'city' => 'Give', 'country_id' => 1],
        ['zipcode' => 7330, 'city' => 'Brande', 'country_id' => 1],
        ['zipcode' => 7361, 'city' => 'Ejstrupholm', 'country_id' => 1],
        ['zipcode' => 7362, 'city' => 'Hampen', 'country_id' => 1],
        ['zipcode' => 7400, 'city' => 'Herning', 'country_id' => 1],
        ['zipcode' => 7430, 'city' => 'Ikast', 'country_id' => 1],
        ['zipcode' => 7441, 'city' => 'Bording', 'country_id' => 1],
        ['zipcode' => 7442, 'city' => 'Engesvang', 'country_id' => 1],
        ['zipcode' => 7451, 'city' => 'Sunds', 'country_id' => 1],
        ['zipcode' => 7470, 'city' => 'Karup J', 'country_id' => 1],
        ['zipcode' => 7480, 'city' => 'Vildbjerg', 'country_id' => 1],
        ['zipcode' => 7490, 'city' => 'Aulum', 'country_id' => 1],
        ['zipcode' => 7500, 'city' => 'Holstebro', 'country_id' => 1],
        ['zipcode' => 7540, 'city' => 'Haderup', 'country_id' => 1],
        ['zipcode' => 7550, 'city' => 'Sørvad', 'country_id' => 1],
        ['zipcode' => 7560, 'city' => 'Hjerm', 'country_id' => 1],
        ['zipcode' => 7570, 'city' => 'Vemb', 'country_id' => 1],
        ['zipcode' => 7600, 'city' => 'Struer', 'country_id' => 1],
        ['zipcode' => 7620, 'city' => 'Lemvig', 'country_id' => 1],
        ['zipcode' => 7650, 'city' => 'Bøvlingbjerg', 'country_id' => 1],
        ['zipcode' => 7660, 'city' => 'Bækmarksbro', 'country_id' => 1],
        ['zipcode' => 7673, 'city' => 'Harboøre', 'country_id' => 1],
        ['zipcode' => 7680, 'city' => 'Thyborøn', 'country_id' => 1],
        ['zipcode' => 7700, 'city' => 'Thisted', 'country_id' => 1],
        ['zipcode' => 7730, 'city' => 'Hanstholm', 'country_id' => 1],
        ['zipcode' => 7741, 'city' => 'Frøstrup', 'country_id' => 1],
        ['zipcode' => 7742, 'city' => 'Vesløs', 'country_id' => 1],
        ['zipcode' => 7752, 'city' => 'Snedsted', 'country_id' => 1],
        ['zipcode' => 7755, 'city' => 'Bedsted Thy', 'country_id' => 1],
        ['zipcode' => 7760, 'city' => 'Hurup Thy', 'country_id' => 1],
        ['zipcode' => 7770, 'city' => 'Vestervig', 'country_id' => 1],
        ['zipcode' => 7790, 'city' => 'Thyholm', 'country_id' => 1],
        ['zipcode' => 7800, 'city' => 'Skive', 'country_id' => 1],
        ['zipcode' => 7830, 'city' => 'Vinderup', 'country_id' => 1],
        ['zipcode' => 7840, 'city' => 'Højslev', 'country_id' => 1],
        ['zipcode' => 7850, 'city' => 'Stoholm Jyll', 'country_id' => 1],
        ['zipcode' => 7860, 'city' => 'Spøttrup', 'country_id' => 1],
        ['zipcode' => 7870, 'city' => 'Roslev', 'country_id' => 1],
        ['zipcode' => 7884, 'city' => 'Fur', 'country_id' => 1],
        ['zipcode' => 7900, 'city' => 'Nykøbing M', 'country_id' => 1],
        ['zipcode' => 7950, 'city' => 'Erslev', 'country_id' => 1],
        ['zipcode' => 7960, 'city' => 'Karby', 'country_id' => 1],
        ['zipcode' => 7970, 'city' => 'Redsted M', 'country_id' => 1],
        ['zipcode' => 7980, 'city' => 'Vils', 'country_id' => 1],
        ['zipcode' => 7990, 'city' => 'Øster Assels', 'country_id' => 1],
        ['zipcode' => 8000, 'city' => 'Aarhus C', 'country_id' => 1],
        ['zipcode' => 8200, 'city' => 'Aarhus N', 'country_id' => 1],
        ['zipcode' => 8210, 'city' => 'Aarhus V', 'country_id' => 1],
        ['zipcode' => 8220, 'city' => 'Brabrand', 'country_id' => 1],
        ['zipcode' => 8230, 'city' => 'Åbyhøj', 'country_id' => 1],
        ['zipcode' => 8240, 'city' => 'Risskov', 'country_id' => 1],
        ['zipcode' => 8250, 'city' => 'Egå', 'country_id' => 1],
        ['zipcode' => 8260, 'city' => 'Viby J', 'country_id' => 1],
        ['zipcode' => 8270, 'city' => 'Højbjerg', 'country_id' => 1],
        ['zipcode' => 8300, 'city' => 'Odder', 'country_id' => 1],
        ['zipcode' => 8305, 'city' => 'Samsø', 'country_id' => 1],
        ['zipcode' => 8310, 'city' => 'Tranbjerg J', 'country_id' => 1],
        ['zipcode' => 8320, 'city' => 'Mårslet', 'country_id' => 1],
        ['zipcode' => 8330, 'city' => 'Beder', 'country_id' => 1],
        ['zipcode' => 8340, 'city' => 'Malling', 'country_id' => 1],
        ['zipcode' => 8350, 'city' => 'Hundslund', 'country_id' => 1],
        ['zipcode' => 8355, 'city' => 'Solbjerg', 'country_id' => 1],
        ['zipcode' => 8361, 'city' => 'Hasselager', 'country_id' => 1],
        ['zipcode' => 8362, 'city' => 'Hørning', 'country_id' => 1],
        ['zipcode' => 8370, 'city' => 'Hadsten', 'country_id' => 1],
        ['zipcode' => 8380, 'city' => 'Trige', 'country_id' => 1],
        ['zipcode' => 8381, 'city' => 'Tilst', 'country_id' => 1],
        ['zipcode' => 8382, 'city' => 'Hinnerup', 'country_id' => 1],
        ['zipcode' => 8400, 'city' => 'Ebeltoft', 'country_id' => 1],
        ['zipcode' => 8410, 'city' => 'Rønde', 'country_id' => 1],
        ['zipcode' => 8420, 'city' => 'Knebel', 'country_id' => 1],
        ['zipcode' => 8444, 'city' => 'Balle', 'country_id' => 1],
        ['zipcode' => 8450, 'city' => 'Hammel', 'country_id' => 1],
        ['zipcode' => 8462, 'city' => 'Harlev J', 'country_id' => 1],
        ['zipcode' => 8464, 'city' => 'Galten', 'country_id' => 1],
        ['zipcode' => 8471, 'city' => 'Sabro', 'country_id' => 1],
        ['zipcode' => 8472, 'city' => 'Sporup', 'country_id' => 1],
        ['zipcode' => 8500, 'city' => 'Grenaa', 'country_id' => 1],
        ['zipcode' => 8520, 'city' => 'Lystrup', 'country_id' => 1],
        ['zipcode' => 8530, 'city' => 'Hjortshøj', 'country_id' => 1],
        ['zipcode' => 8541, 'city' => 'Skødstrup', 'country_id' => 1],
        ['zipcode' => 8543, 'city' => 'Hornslet', 'country_id' => 1],
        ['zipcode' => 8544, 'city' => 'Mørke', 'country_id' => 1],
        ['zipcode' => 8550, 'city' => 'Ryomgård', 'country_id' => 1],
        ['zipcode' => 8560, 'city' => 'Kolind', 'country_id' => 1],
        ['zipcode' => 8570, 'city' => 'Trustrup', 'country_id' => 1],
        ['zipcode' => 8581, 'city' => 'Nimtofte', 'country_id' => 1],
        ['zipcode' => 8585, 'city' => 'Glesborg', 'country_id' => 1],
        ['zipcode' => 8586, 'city' => 'Ørum Djurs', 'country_id' => 1],
        ['zipcode' => 8592, 'city' => 'Anholt', 'country_id' => 1],
        ['zipcode' => 8600, 'city' => 'Silkeborg', 'country_id' => 1],
        ['zipcode' => 8620, 'city' => 'Kjellerup', 'country_id' => 1],
        ['zipcode' => 8632, 'city' => 'Lemming', 'country_id' => 1],
        ['zipcode' => 8641, 'city' => 'Sorring', 'country_id' => 1],
        ['zipcode' => 8643, 'city' => 'Ans By', 'country_id' => 1],
        ['zipcode' => 8653, 'city' => 'Them', 'country_id' => 1],
        ['zipcode' => 8654, 'city' => 'Bryrup', 'country_id' => 1],
        ['zipcode' => 8660, 'city' => 'Skanderborg', 'country_id' => 1],
        ['zipcode' => 8670, 'city' => 'Låsby', 'country_id' => 1],
        ['zipcode' => 8680, 'city' => 'Ry', 'country_id' => 1],
        ['zipcode' => 8700, 'city' => 'Horsens', 'country_id' => 1],
        ['zipcode' => 8721, 'city' => 'Daugård', 'country_id' => 1],
        ['zipcode' => 8722, 'city' => 'Hedensted', 'country_id' => 1],
        ['zipcode' => 8723, 'city' => 'Løsning', 'country_id' => 1],
        ['zipcode' => 8732, 'city' => 'Hovedgård', 'country_id' => 1],
        ['zipcode' => 8740, 'city' => 'Brædstrup', 'country_id' => 1],
        ['zipcode' => 8751, 'city' => 'Gedved', 'country_id' => 1],
        ['zipcode' => 8752, 'city' => 'Østbirk', 'country_id' => 1],
        ['zipcode' => 8762, 'city' => 'Flemming', 'country_id' => 1],
        ['zipcode' => 8763, 'city' => 'Rask Mølle', 'country_id' => 1],
        ['zipcode' => 8765, 'city' => 'Klovborg', 'country_id' => 1],
        ['zipcode' => 8766, 'city' => 'Nørre Snede', 'country_id' => 1],
        ['zipcode' => 8781, 'city' => 'Stenderup', 'country_id' => 1],
        ['zipcode' => 8783, 'city' => 'Hornsyld', 'country_id' => 1],
        ['zipcode' => 8789, 'city' => 'Endelave', 'country_id' => 1],
        ['zipcode' => 8799, 'city' => 'Tunø', 'country_id' => 1],
        ['zipcode' => 8800, 'city' => 'Viborg', 'country_id' => 1],
        ['zipcode' => 8830, 'city' => 'Tjele', 'country_id' => 1],
        ['zipcode' => 8831, 'city' => 'Løgstrup', 'country_id' => 1],
        ['zipcode' => 8832, 'city' => 'Skals', 'country_id' => 1],
        ['zipcode' => 8840, 'city' => 'Rødkærsbro', 'country_id' => 1],
        ['zipcode' => 8850, 'city' => 'Bjerringbro', 'country_id' => 1],
        ['zipcode' => 8860, 'city' => 'Ulstrup', 'country_id' => 1],
        ['zipcode' => 8870, 'city' => 'Langå', 'country_id' => 1],
        ['zipcode' => 8881, 'city' => 'Thorsø', 'country_id' => 1],
        ['zipcode' => 8882, 'city' => 'Fårvang', 'country_id' => 1],
        ['zipcode' => 8883, 'city' => 'Gjern', 'country_id' => 1],
        ['zipcode' => 8900, 'city' => 'Randers C', 'country_id' => 1],
        ['zipcode' => 8920, 'city' => 'Randers NV', 'country_id' => 1],
        ['zipcode' => 8930, 'city' => 'Randers NØ', 'country_id' => 1],
        ['zipcode' => 8940, 'city' => 'Randers SV', 'country_id' => 1],
        ['zipcode' => 8950, 'city' => 'Ørsted', 'country_id' => 1],
        ['zipcode' => 8960, 'city' => 'Randers SØ', 'country_id' => 1],
        ['zipcode' => 8961, 'city' => 'Allingåbro', 'country_id' => 1],
        ['zipcode' => 8963, 'city' => 'Auning', 'country_id' => 1],
        ['zipcode' => 8970, 'city' => 'Havndal', 'country_id' => 1],
        ['zipcode' => 8981, 'city' => 'Spentrup', 'country_id' => 1],
        ['zipcode' => 8983, 'city' => 'Gjerlev J', 'country_id' => 1],
        ['zipcode' => 8990, 'city' => 'Fårup', 'country_id' => 1],
        ['zipcode' => 9000, 'city' => 'Aalborg', 'country_id' => 1],
        ['zipcode' => 9200, 'city' => 'Aalborg SV', 'country_id' => 1],
        ['zipcode' => 9210, 'city' => 'Aalborg SØ', 'country_id' => 1],
        ['zipcode' => 9220, 'city' => 'Aalborg Øst', 'country_id' => 1],
        ['zipcode' => 9230, 'city' => 'Svenstrup J', 'country_id' => 1],
        ['zipcode' => 9240, 'city' => 'Nibe', 'country_id' => 1],
        ['zipcode' => 9260, 'city' => 'Gistrup', 'country_id' => 1],
        ['zipcode' => 9270, 'city' => 'Klarup', 'country_id' => 1],
        ['zipcode' => 9280, 'city' => 'Storvorde', 'country_id' => 1],
        ['zipcode' => 9293, 'city' => 'Kongerslev', 'country_id' => 1],
        ['zipcode' => 9300, 'city' => 'Sæby', 'country_id' => 1],
        ['zipcode' => 9310, 'city' => 'Vodskov', 'country_id' => 1],
        ['zipcode' => 9320, 'city' => 'Hjallerup', 'country_id' => 1],
        ['zipcode' => 9330, 'city' => 'Dronninglund', 'country_id' => 1],
        ['zipcode' => 9340, 'city' => 'Asaa', 'country_id' => 1],
        ['zipcode' => 9352, 'city' => 'Dybvad', 'country_id' => 1],
        ['zipcode' => 9362, 'city' => 'Gandrup', 'country_id' => 1],
        ['zipcode' => 9370, 'city' => 'Hals', 'country_id' => 1],
        ['zipcode' => 9380, 'city' => 'Vestbjerg', 'country_id' => 1],
        ['zipcode' => 9381, 'city' => 'Sulsted', 'country_id' => 1],
        ['zipcode' => 9382, 'city' => 'Tylstrup', 'country_id' => 1],
        ['zipcode' => 9400, 'city' => 'Nørresundby', 'country_id' => 1],
        ['zipcode' => 9430, 'city' => 'Vadum', 'country_id' => 1],
        ['zipcode' => 9440, 'city' => 'Aabybro', 'country_id' => 1],
        ['zipcode' => 9460, 'city' => 'Brovst', 'country_id' => 1],
        ['zipcode' => 9480, 'city' => 'Løkken', 'country_id' => 1],
        ['zipcode' => 9490, 'city' => 'Pandrup', 'country_id' => 1],
        ['zipcode' => 9492, 'city' => 'Blokhus', 'country_id' => 1],
        ['zipcode' => 9493, 'city' => 'Saltum', 'country_id' => 1],
        ['zipcode' => 9500, 'city' => 'Hobro', 'country_id' => 1],
        ['zipcode' => 9510, 'city' => 'Arden', 'country_id' => 1],
        ['zipcode' => 9520, 'city' => 'Skørping', 'country_id' => 1],
        ['zipcode' => 9530, 'city' => 'Støvring', 'country_id' => 1],
        ['zipcode' => 9541, 'city' => 'Suldrup', 'country_id' => 1],
        ['zipcode' => 9550, 'city' => 'Mariager', 'country_id' => 1],
        ['zipcode' => 9560, 'city' => 'Hadsund', 'country_id' => 1],
        ['zipcode' => 9574, 'city' => 'Bælum', 'country_id' => 1],
        ['zipcode' => 9575, 'city' => 'Terndrup', 'country_id' => 1],
        ['zipcode' => 9600, 'city' => 'Aars', 'country_id' => 1],
        ['zipcode' => 9610, 'city' => 'Nørager', 'country_id' => 1],
        ['zipcode' => 9620, 'city' => 'Aalestrup', 'country_id' => 1],
        ['zipcode' => 9631, 'city' => 'Gedsted', 'country_id' => 1],
        ['zipcode' => 9632, 'city' => 'Møldrup', 'country_id' => 1],
        ['zipcode' => 9640, 'city' => 'Farsø', 'country_id' => 1],
        ['zipcode' => 9670, 'city' => 'Løgstør', 'country_id' => 1],
        ['zipcode' => 9681, 'city' => 'Ranum', 'country_id' => 1],
        ['zipcode' => 9690, 'city' => 'Fjerritslev', 'country_id' => 1],
        ['zipcode' => 9700, 'city' => 'Brønderslev', 'country_id' => 1],
        ['zipcode' => 9740, 'city' => 'Jerslev J', 'country_id' => 1],
        ['zipcode' => 9750, 'city' => 'Østervrå', 'country_id' => 1],
        ['zipcode' => 9760, 'city' => 'Vrå', 'country_id' => 1],
        ['zipcode' => 9800, 'city' => 'Hjørring', 'country_id' => 1],
        ['zipcode' => 9830, 'city' => 'Tårs', 'country_id' => 1],
        ['zipcode' => 9850, 'city' => 'Hirtshals', 'country_id' => 1],
        ['zipcode' => 9870, 'city' => 'Sindal', 'country_id' => 1],
        ['zipcode' => 9881, 'city' => 'Bindslev', 'country_id' => 1],
        ['zipcode' => 9900, 'city' => 'Frederikshavn', 'country_id' => 1],
        ['zipcode' => 9940, 'city' => 'Læsø', 'country_id' => 1],
        ['zipcode' => 9970, 'city' => 'Strandby', 'country_id' => 1],
        ['zipcode' => 9981, 'city' => 'Jerup', 'country_id' => 1],
        ['zipcode' => 9982, 'city' => 'Ålbæk', 'country_id' => 1],
        ['zipcode' => 9990, 'city' => 'Skagen', 'country_id' => 1],
    ];
}
